name: 'PR Labeler and Commenter'
description: 'Automatically labels and comments on pull requests based on the number of changes.'
inputs:
  repo-token:
    description: 'The GitHub token for authentication.'
    required: true
  max-changes-for-label:
    description: 'The maximum number of changes a PR can have before being labeled.'
    required: true
    default: '2'
  label-message:
    description: 'Custom message to post on PRs that are labeled as potential spam.'
    required: false
    default: 'This PR has been automatically labeled as "Potential Spam" due to its size. Please review.'
runs:
  using: 'composite'
  steps:
    - name: Label and comment on PRs
      shell: pwsh
      run: pwsh -File ./.github/scripts/AntiSpamPRLabeler.ps1 -GITHUB_TOKEN ${{ inputs.repo-token }} -MAX_CHANGES_FOR_LABEL ${{ inputs.max-changes-for-label }} -LABEL_MESSAGE "${{ inputs.label-message }}"
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}